from os.path import join as osjoin
import pandas as pd

# store the local path to the dropbox folder in the 'PROJ_HOME_DIR' file.
PROJ_HOME = open('PROJ_HOME_DIR').read().strip()
DATA_DIR = osjoin(PROJ_HOME, 'Data')
RAW_DIR = osjoin(DATA_DIR, 'Raw')
ADDITIONAL_DIR = osjoin(DATA_DIR, 'Additional_data')
DERIVED_DIR = osjoin(DATA_DIR, 'Derived')
PROCESSED_DIR = osjoin(DERIVED_DIR, 'Processed')

#####################
# RAW DATA, AA
#####################
RAW_AADATA_EXCEL = osjoin(RAW_DIR, "AAD2016.01.814.xlsx")
AADATA_AS_CSV = osjoin(PROCESSED_DIR, "aadata2016.csv")
AADATA_CSV_WITH_PREFIX = osjoin(PROCESSED_DIR, "aadata2016_prefixed.csv")


#####################
# RAW DATA, RMP
#####################
RAW_RMP = osjoin(RAW_DIR, "rmp_professors.csv")
RMP_CSV_WITH_PREFIX = osjoin(PROCESSED_DIR, "rmp2017_prefixed.csv")


rule all:
    input:
        AADATA_AS_CSV,
        AADATA_CSV_WITH_PREFIX,
        RMP_CSV_WITH_PREFIX


rule convert_aadata_excel_to_csv:
    input: RAW_AADATA_EXCEL,
    output: AADATA_AS_CSV,
    shell: "Rscript scripts/excel_to_csv.R {input} {output}"

rule add_prefix_to_aadata_columns:
    input: rules.convert_aadata_excel_to_csv.output
    output: AADATA_CSV_WITH_PREFIX
    shell: "Rscript scripts/apply_prefix_to_columns.R {input} \"AA.\" {output}"

rule add_prefix_to_rmp_columns:
    input: RAW_RMP
    output: RMP_CSV_WITH_PREFIX
    shell: "Rscript scripts/apply_prefix_to_columns.R {input} \"RMP.\" {output}"
